version: '3.7'

services:
  flask-api:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        - FLASK_ENV=${FLASK_ENV}
        - FLASK_PORT=${FLASK_PORT}
    restart: unless-stopped
    container_name: flask-api
    image: hrlab/flask-api:0.0.0
    ports:
      - 0.0.0.0:${FLASK_PORT}:${FLASK_PORT}
    expose:
      - ${FLASK_PORT}
    networks:
      - app-net-back

  web:
    container_name: react-frontend
    restart: unless-stopped
    build:
      context: .
      dockerfile: ${DOCKERFILE_WEB}
      args:
        - FLASK_ENV=${FLASK_ENV}
        - FLASK_HOST=0.0.0.0
        - REACT_SCRIPTS_VERSION=${REACT_SCRIPTS_VERSION}
        - NGINX_PORT=${NGINX_PORT}
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - ${PORT_EXPOSE}:${NGINX_PORT}
    networks:
      - app-net-front

networks:
  app-net-back:
  app-net-front:
