version: '3.7'

services:
  db:
    image: mysql:8.0.24
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 0.0.0.0:${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - ./data:/app/data
    networks:
      - app-net
  flask-api:
    build:
      context: .
      dockerfile: ${DOCKERFILE}
      args:
        - FLASK_ENV=${FLASK_ENV}
        - FLASK_PORT=${FLASK_PORT}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_PORT=${MYSQL_PORT}
    restart: unless-stopped
    links:
      - db
    container_name: flask-api
    image: hrlab/flask-api:0.0.0
    ports:
      - 0.0.0.0:${FLASK_PORT}:${FLASK_PORT}
    expose:
      - ${FLASK_PORT}
    volumes:
      - ./src:/app/src
    networks:
      - app-net

networks:
  app-net:
