FROM node:15.14.0-alpine3.13

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
# You can keep the installation silent with the --silent flag
COPY web/package.json ./
COPY web/package-lock.json ./
RUN npm install
RUN npm install react-scripts@${REACT_SCRIPTS_VERSION} -g

# add app
COPY web/* ./

# start app
CMD ["npm", "start"]