FROM node:15.14.0-alpine3.13 as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY web/package.json ./
COPY web/package-lock.json ./
RUN npm ci
RUN npm install react-scripts@${REACT_SCRIPTS_VERSION} -g
COPY ./web/* ./
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE ${NGINX_PORT}

CMD ["nginx", "-g", "daemon off;"]